#%RAML 1.0 NamedExample
value: |
  {
    "id":11,
      "title":"Fix Duplicate Requests",
      "description":"Filter duplicate API requests with an Idempotency Token on api v3",
      "statusId":1,
      "creatorId":5,
      "assigneeId":5,
      "projectId":3,
      "type":"BUG",
      "dateCreated":"2020-01-19 03:14:07"
  }